scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: box_filter
      type: walker_laser_filter/LaserScanInboxFilter
      params:
        box_frame: base_link
        remove_outside: true
        min_x: -0.4
        min_y: -0.4
        min_z: -0.4
        max_x: 0.4
        max_y: 0.4
        max_z: 0.4